# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.9

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/local/bin/cmake

# The command to remove a file.
RM = /opt/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/kpadhikari/KpInstalls/Geant4/ExamplesBld/HadronTherapyKp2/Source/hadrontherapy

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/kpadhikari/KpInstalls/Geant4/ExamplesBld/HadronTherapyKp2

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/opt/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/opt/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/opt/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/opt/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/opt/local/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/opt/local/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/local/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/kpadhikari/KpInstalls/Geant4/ExamplesBld/HadronTherapyKp2/CMakeFiles /Users/kpadhikari/KpInstalls/Geant4/ExamplesBld/HadronTherapyKp2/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/kpadhikari/KpInstalls/Geant4/ExamplesBld/HadronTherapyKp2/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named hadrontherapy

# Build rule for target.
hadrontherapy: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hadrontherapy
.PHONY : hadrontherapy

# fast build rule for target.
hadrontherapy/fast:
	$(MAKE) -f CMakeFiles/hadrontherapy.dir/build.make CMakeFiles/hadrontherapy.dir/build
.PHONY : hadrontherapy/fast

hadrontherapy.o: hadrontherapy.cc.o

.PHONY : hadrontherapy.o

# target to build an object file
hadrontherapy.cc.o:
	$(MAKE) -f CMakeFiles/hadrontherapy.dir/build.make CMakeFiles/hadrontherapy.dir/hadrontherapy.cc.o
.PHONY : hadrontherapy.cc.o

hadrontherapy.i: hadrontherapy.cc.i

.PHONY : hadrontherapy.i

# target to preprocess a source file
hadrontherapy.cc.i:
	$(MAKE) -f CMakeFiles/hadrontherapy.dir/build.make CMakeFiles/hadrontherapy.dir/hadrontherapy.cc.i
.PHONY : hadrontherapy.cc.i

hadrontherapy.s: hadrontherapy.cc.s

.PHONY : hadrontherapy.s

# target to generate assembly for a file
hadrontherapy.cc.s:
	$(MAKE) -f CMakeFiles/hadrontherapy.dir/build.make CMakeFiles/hadrontherapy.dir/hadrontherapy.cc.s
.PHONY : hadrontherapy.cc.s

src/HadrontherapyActionInitialization.o: src/HadrontherapyActionInitialization.cc.o

.PHONY : src/HadrontherapyActionInitialization.o

# target to build an object file
src/HadrontherapyActionInitialization.cc.o:
	$(MAKE) -f CMakeFiles/hadrontherapy.dir/build.make CMakeFiles/hadrontherapy.dir/src/HadrontherapyActionInitialization.cc.o
.PHONY : src/HadrontherapyActionInitialization.cc.o

src/HadrontherapyActionInitialization.i: src/HadrontherapyActionInitialization.cc.i

.PHONY : src/HadrontherapyActionInitialization.i

# target to preprocess a source file
src/HadrontherapyActionInitialization.cc.i:
	$(MAKE) -f CMakeFiles/hadrontherapy.dir/build.make CMakeFiles/hadrontherapy.dir/src/HadrontherapyActionInitialization.cc.i
.PHONY : src/HadrontherapyActionInitialization.cc.i

src/HadrontherapyActionInitialization.s: src/HadrontherapyActionInitialization.cc.s

.PHONY : src/HadrontherapyActionInitialization.s

# target to generate assembly for a file
src/HadrontherapyActionInitialization.cc.s:
	$(MAKE) -f CMakeFiles/hadrontherapy.dir/build.make CMakeFiles/hadrontherapy.dir/src/HadrontherapyActionInitialization.cc.s
.PHONY : src/HadrontherapyActionInitialization.cc.s

src/HadrontherapyDetectorHit.o: src/HadrontherapyDetectorHit.cc.o

.PHONY : src/HadrontherapyDetectorHit.o

# target to build an object file
src/HadrontherapyDetectorHit.cc.o:
	$(MAKE) -f CMakeFiles/hadrontherapy.dir/build.make CMakeFiles/hadrontherapy.dir/src/HadrontherapyDetectorHit.cc.o
.PHONY : src/HadrontherapyDetectorHit.cc.o

src/HadrontherapyDetectorHit.i: src/HadrontherapyDetectorHit.cc.i

.PHONY : src/HadrontherapyDetectorHit.i

# target to preprocess a source file
src/HadrontherapyDetectorHit.cc.i:
	$(MAKE) -f CMakeFiles/hadrontherapy.dir/build.make CMakeFiles/hadrontherapy.dir/src/HadrontherapyDetectorHit.cc.i
.PHONY : src/HadrontherapyDetectorHit.cc.i

src/HadrontherapyDetectorHit.s: src/HadrontherapyDetectorHit.cc.s

.PHONY : src/HadrontherapyDetectorHit.s

# target to generate assembly for a file
src/HadrontherapyDetectorHit.cc.s:
	$(MAKE) -f CMakeFiles/hadrontherapy.dir/build.make CMakeFiles/hadrontherapy.dir/src/HadrontherapyDetectorHit.cc.s
.PHONY : src/HadrontherapyDetectorHit.cc.s

src/HadrontherapyDetectorMessenger.o: src/HadrontherapyDetectorMessenger.cc.o

.PHONY : src/HadrontherapyDetectorMessenger.o

# target to build an object file
src/HadrontherapyDetectorMessenger.cc.o:
	$(MAKE) -f CMakeFiles/hadrontherapy.dir/build.make CMakeFiles/hadrontherapy.dir/src/HadrontherapyDetectorMessenger.cc.o
.PHONY : src/HadrontherapyDetectorMessenger.cc.o

src/HadrontherapyDetectorMessenger.i: src/HadrontherapyDetectorMessenger.cc.i

.PHONY : src/HadrontherapyDetectorMessenger.i

# target to preprocess a source file
src/HadrontherapyDetectorMessenger.cc.i:
	$(MAKE) -f CMakeFiles/hadrontherapy.dir/build.make CMakeFiles/hadrontherapy.dir/src/HadrontherapyDetectorMessenger.cc.i
.PHONY : src/HadrontherapyDetectorMessenger.cc.i

src/HadrontherapyDetectorMessenger.s: src/HadrontherapyDetectorMessenger.cc.s

.PHONY : src/HadrontherapyDetectorMessenger.s

# target to generate assembly for a file
src/HadrontherapyDetectorMessenger.cc.s:
	$(MAKE) -f CMakeFiles/hadrontherapy.dir/build.make CMakeFiles/hadrontherapy.dir/src/HadrontherapyDetectorMessenger.cc.s
.PHONY : src/HadrontherapyDetectorMessenger.cc.s

src/HadrontherapyDetectorROGeometry.o: src/HadrontherapyDetectorROGeometry.cc.o

.PHONY : src/HadrontherapyDetectorROGeometry.o

# target to build an object file
src/HadrontherapyDetectorROGeometry.cc.o:
	$(MAKE) -f CMakeFiles/hadrontherapy.dir/build.make CMakeFiles/hadrontherapy.dir/src/HadrontherapyDetectorROGeometry.cc.o
.PHONY : src/HadrontherapyDetectorROGeometry.cc.o

src/HadrontherapyDetectorROGeometry.i: src/HadrontherapyDetectorROGeometry.cc.i

.PHONY : src/HadrontherapyDetectorROGeometry.i

# target to preprocess a source file
src/HadrontherapyDetectorROGeometry.cc.i:
	$(MAKE) -f CMakeFiles/hadrontherapy.dir/build.make CMakeFiles/hadrontherapy.dir/src/HadrontherapyDetectorROGeometry.cc.i
.PHONY : src/HadrontherapyDetectorROGeometry.cc.i

src/HadrontherapyDetectorROGeometry.s: src/HadrontherapyDetectorROGeometry.cc.s

.PHONY : src/HadrontherapyDetectorROGeometry.s

# target to generate assembly for a file
src/HadrontherapyDetectorROGeometry.cc.s:
	$(MAKE) -f CMakeFiles/hadrontherapy.dir/build.make CMakeFiles/hadrontherapy.dir/src/HadrontherapyDetectorROGeometry.cc.s
.PHONY : src/HadrontherapyDetectorROGeometry.cc.s

src/HadrontherapyDetectorSD.o: src/HadrontherapyDetectorSD.cc.o

.PHONY : src/HadrontherapyDetectorSD.o

# target to build an object file
src/HadrontherapyDetectorSD.cc.o:
	$(MAKE) -f CMakeFiles/hadrontherapy.dir/build.make CMakeFiles/hadrontherapy.dir/src/HadrontherapyDetectorSD.cc.o
.PHONY : src/HadrontherapyDetectorSD.cc.o

src/HadrontherapyDetectorSD.i: src/HadrontherapyDetectorSD.cc.i

.PHONY : src/HadrontherapyDetectorSD.i

# target to preprocess a source file
src/HadrontherapyDetectorSD.cc.i:
	$(MAKE) -f CMakeFiles/hadrontherapy.dir/build.make CMakeFiles/hadrontherapy.dir/src/HadrontherapyDetectorSD.cc.i
.PHONY : src/HadrontherapyDetectorSD.cc.i

src/HadrontherapyDetectorSD.s: src/HadrontherapyDetectorSD.cc.s

.PHONY : src/HadrontherapyDetectorSD.s

# target to generate assembly for a file
src/HadrontherapyDetectorSD.cc.s:
	$(MAKE) -f CMakeFiles/hadrontherapy.dir/build.make CMakeFiles/hadrontherapy.dir/src/HadrontherapyDetectorSD.cc.s
.PHONY : src/HadrontherapyDetectorSD.cc.s

src/HadrontherapyEventAction.o: src/HadrontherapyEventAction.cc.o

.PHONY : src/HadrontherapyEventAction.o

# target to build an object file
src/HadrontherapyEventAction.cc.o:
	$(MAKE) -f CMakeFiles/hadrontherapy.dir/build.make CMakeFiles/hadrontherapy.dir/src/HadrontherapyEventAction.cc.o
.PHONY : src/HadrontherapyEventAction.cc.o

src/HadrontherapyEventAction.i: src/HadrontherapyEventAction.cc.i

.PHONY : src/HadrontherapyEventAction.i

# target to preprocess a source file
src/HadrontherapyEventAction.cc.i:
	$(MAKE) -f CMakeFiles/hadrontherapy.dir/build.make CMakeFiles/hadrontherapy.dir/src/HadrontherapyEventAction.cc.i
.PHONY : src/HadrontherapyEventAction.cc.i

src/HadrontherapyEventAction.s: src/HadrontherapyEventAction.cc.s

.PHONY : src/HadrontherapyEventAction.s

# target to generate assembly for a file
src/HadrontherapyEventAction.cc.s:
	$(MAKE) -f CMakeFiles/hadrontherapy.dir/build.make CMakeFiles/hadrontherapy.dir/src/HadrontherapyEventAction.cc.s
.PHONY : src/HadrontherapyEventAction.cc.s

src/HadrontherapyLet.o: src/HadrontherapyLet.cc.o

.PHONY : src/HadrontherapyLet.o

# target to build an object file
src/HadrontherapyLet.cc.o:
	$(MAKE) -f CMakeFiles/hadrontherapy.dir/build.make CMakeFiles/hadrontherapy.dir/src/HadrontherapyLet.cc.o
.PHONY : src/HadrontherapyLet.cc.o

src/HadrontherapyLet.i: src/HadrontherapyLet.cc.i

.PHONY : src/HadrontherapyLet.i

# target to preprocess a source file
src/HadrontherapyLet.cc.i:
	$(MAKE) -f CMakeFiles/hadrontherapy.dir/build.make CMakeFiles/hadrontherapy.dir/src/HadrontherapyLet.cc.i
.PHONY : src/HadrontherapyLet.cc.i

src/HadrontherapyLet.s: src/HadrontherapyLet.cc.s

.PHONY : src/HadrontherapyLet.s

# target to generate assembly for a file
src/HadrontherapyLet.cc.s:
	$(MAKE) -f CMakeFiles/hadrontherapy.dir/build.make CMakeFiles/hadrontherapy.dir/src/HadrontherapyLet.cc.s
.PHONY : src/HadrontherapyLet.cc.s

src/HadrontherapyMatrix.o: src/HadrontherapyMatrix.cc.o

.PHONY : src/HadrontherapyMatrix.o

# target to build an object file
src/HadrontherapyMatrix.cc.o:
	$(MAKE) -f CMakeFiles/hadrontherapy.dir/build.make CMakeFiles/hadrontherapy.dir/src/HadrontherapyMatrix.cc.o
.PHONY : src/HadrontherapyMatrix.cc.o

src/HadrontherapyMatrix.i: src/HadrontherapyMatrix.cc.i

.PHONY : src/HadrontherapyMatrix.i

# target to preprocess a source file
src/HadrontherapyMatrix.cc.i:
	$(MAKE) -f CMakeFiles/hadrontherapy.dir/build.make CMakeFiles/hadrontherapy.dir/src/HadrontherapyMatrix.cc.i
.PHONY : src/HadrontherapyMatrix.cc.i

src/HadrontherapyMatrix.s: src/HadrontherapyMatrix.cc.s

.PHONY : src/HadrontherapyMatrix.s

# target to generate assembly for a file
src/HadrontherapyMatrix.cc.s:
	$(MAKE) -f CMakeFiles/hadrontherapy.dir/build.make CMakeFiles/hadrontherapy.dir/src/HadrontherapyMatrix.cc.s
.PHONY : src/HadrontherapyMatrix.cc.s

src/HadrontherapyPhysicsList.o: src/HadrontherapyPhysicsList.cc.o

.PHONY : src/HadrontherapyPhysicsList.o

# target to build an object file
src/HadrontherapyPhysicsList.cc.o:
	$(MAKE) -f CMakeFiles/hadrontherapy.dir/build.make CMakeFiles/hadrontherapy.dir/src/HadrontherapyPhysicsList.cc.o
.PHONY : src/HadrontherapyPhysicsList.cc.o

src/HadrontherapyPhysicsList.i: src/HadrontherapyPhysicsList.cc.i

.PHONY : src/HadrontherapyPhysicsList.i

# target to preprocess a source file
src/HadrontherapyPhysicsList.cc.i:
	$(MAKE) -f CMakeFiles/hadrontherapy.dir/build.make CMakeFiles/hadrontherapy.dir/src/HadrontherapyPhysicsList.cc.i
.PHONY : src/HadrontherapyPhysicsList.cc.i

src/HadrontherapyPhysicsList.s: src/HadrontherapyPhysicsList.cc.s

.PHONY : src/HadrontherapyPhysicsList.s

# target to generate assembly for a file
src/HadrontherapyPhysicsList.cc.s:
	$(MAKE) -f CMakeFiles/hadrontherapy.dir/build.make CMakeFiles/hadrontherapy.dir/src/HadrontherapyPhysicsList.cc.s
.PHONY : src/HadrontherapyPhysicsList.cc.s

src/HadrontherapyPrimaryGeneratorAction.o: src/HadrontherapyPrimaryGeneratorAction.cc.o

.PHONY : src/HadrontherapyPrimaryGeneratorAction.o

# target to build an object file
src/HadrontherapyPrimaryGeneratorAction.cc.o:
	$(MAKE) -f CMakeFiles/hadrontherapy.dir/build.make CMakeFiles/hadrontherapy.dir/src/HadrontherapyPrimaryGeneratorAction.cc.o
.PHONY : src/HadrontherapyPrimaryGeneratorAction.cc.o

src/HadrontherapyPrimaryGeneratorAction.i: src/HadrontherapyPrimaryGeneratorAction.cc.i

.PHONY : src/HadrontherapyPrimaryGeneratorAction.i

# target to preprocess a source file
src/HadrontherapyPrimaryGeneratorAction.cc.i:
	$(MAKE) -f CMakeFiles/hadrontherapy.dir/build.make CMakeFiles/hadrontherapy.dir/src/HadrontherapyPrimaryGeneratorAction.cc.i
.PHONY : src/HadrontherapyPrimaryGeneratorAction.cc.i

src/HadrontherapyPrimaryGeneratorAction.s: src/HadrontherapyPrimaryGeneratorAction.cc.s

.PHONY : src/HadrontherapyPrimaryGeneratorAction.s

# target to generate assembly for a file
src/HadrontherapyPrimaryGeneratorAction.cc.s:
	$(MAKE) -f CMakeFiles/hadrontherapy.dir/build.make CMakeFiles/hadrontherapy.dir/src/HadrontherapyPrimaryGeneratorAction.cc.s
.PHONY : src/HadrontherapyPrimaryGeneratorAction.cc.s

src/HadrontherapyRunAction.o: src/HadrontherapyRunAction.cc.o

.PHONY : src/HadrontherapyRunAction.o

# target to build an object file
src/HadrontherapyRunAction.cc.o:
	$(MAKE) -f CMakeFiles/hadrontherapy.dir/build.make CMakeFiles/hadrontherapy.dir/src/HadrontherapyRunAction.cc.o
.PHONY : src/HadrontherapyRunAction.cc.o

src/HadrontherapyRunAction.i: src/HadrontherapyRunAction.cc.i

.PHONY : src/HadrontherapyRunAction.i

# target to preprocess a source file
src/HadrontherapyRunAction.cc.i:
	$(MAKE) -f CMakeFiles/hadrontherapy.dir/build.make CMakeFiles/hadrontherapy.dir/src/HadrontherapyRunAction.cc.i
.PHONY : src/HadrontherapyRunAction.cc.i

src/HadrontherapyRunAction.s: src/HadrontherapyRunAction.cc.s

.PHONY : src/HadrontherapyRunAction.s

# target to generate assembly for a file
src/HadrontherapyRunAction.cc.s:
	$(MAKE) -f CMakeFiles/hadrontherapy.dir/build.make CMakeFiles/hadrontherapy.dir/src/HadrontherapyRunAction.cc.s
.PHONY : src/HadrontherapyRunAction.cc.s

src/HadrontherapyStepMax.o: src/HadrontherapyStepMax.cc.o

.PHONY : src/HadrontherapyStepMax.o

# target to build an object file
src/HadrontherapyStepMax.cc.o:
	$(MAKE) -f CMakeFiles/hadrontherapy.dir/build.make CMakeFiles/hadrontherapy.dir/src/HadrontherapyStepMax.cc.o
.PHONY : src/HadrontherapyStepMax.cc.o

src/HadrontherapyStepMax.i: src/HadrontherapyStepMax.cc.i

.PHONY : src/HadrontherapyStepMax.i

# target to preprocess a source file
src/HadrontherapyStepMax.cc.i:
	$(MAKE) -f CMakeFiles/hadrontherapy.dir/build.make CMakeFiles/hadrontherapy.dir/src/HadrontherapyStepMax.cc.i
.PHONY : src/HadrontherapyStepMax.cc.i

src/HadrontherapyStepMax.s: src/HadrontherapyStepMax.cc.s

.PHONY : src/HadrontherapyStepMax.s

# target to generate assembly for a file
src/HadrontherapyStepMax.cc.s:
	$(MAKE) -f CMakeFiles/hadrontherapy.dir/build.make CMakeFiles/hadrontherapy.dir/src/HadrontherapyStepMax.cc.s
.PHONY : src/HadrontherapyStepMax.cc.s

src/HadrontherapySteppingAction.o: src/HadrontherapySteppingAction.cc.o

.PHONY : src/HadrontherapySteppingAction.o

# target to build an object file
src/HadrontherapySteppingAction.cc.o:
	$(MAKE) -f CMakeFiles/hadrontherapy.dir/build.make CMakeFiles/hadrontherapy.dir/src/HadrontherapySteppingAction.cc.o
.PHONY : src/HadrontherapySteppingAction.cc.o

src/HadrontherapySteppingAction.i: src/HadrontherapySteppingAction.cc.i

.PHONY : src/HadrontherapySteppingAction.i

# target to preprocess a source file
src/HadrontherapySteppingAction.cc.i:
	$(MAKE) -f CMakeFiles/hadrontherapy.dir/build.make CMakeFiles/hadrontherapy.dir/src/HadrontherapySteppingAction.cc.i
.PHONY : src/HadrontherapySteppingAction.cc.i

src/HadrontherapySteppingAction.s: src/HadrontherapySteppingAction.cc.s

.PHONY : src/HadrontherapySteppingAction.s

# target to generate assembly for a file
src/HadrontherapySteppingAction.cc.s:
	$(MAKE) -f CMakeFiles/hadrontherapy.dir/build.make CMakeFiles/hadrontherapy.dir/src/HadrontherapySteppingAction.cc.s
.PHONY : src/HadrontherapySteppingAction.cc.s

src/PassiveProtonBeamLine.o: src/PassiveProtonBeamLine.cc.o

.PHONY : src/PassiveProtonBeamLine.o

# target to build an object file
src/PassiveProtonBeamLine.cc.o:
	$(MAKE) -f CMakeFiles/hadrontherapy.dir/build.make CMakeFiles/hadrontherapy.dir/src/PassiveProtonBeamLine.cc.o
.PHONY : src/PassiveProtonBeamLine.cc.o

src/PassiveProtonBeamLine.i: src/PassiveProtonBeamLine.cc.i

.PHONY : src/PassiveProtonBeamLine.i

# target to preprocess a source file
src/PassiveProtonBeamLine.cc.i:
	$(MAKE) -f CMakeFiles/hadrontherapy.dir/build.make CMakeFiles/hadrontherapy.dir/src/PassiveProtonBeamLine.cc.i
.PHONY : src/PassiveProtonBeamLine.cc.i

src/PassiveProtonBeamLine.s: src/PassiveProtonBeamLine.cc.s

.PHONY : src/PassiveProtonBeamLine.s

# target to generate assembly for a file
src/PassiveProtonBeamLine.cc.s:
	$(MAKE) -f CMakeFiles/hadrontherapy.dir/build.make CMakeFiles/hadrontherapy.dir/src/PassiveProtonBeamLine.cc.s
.PHONY : src/PassiveProtonBeamLine.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... install"
	@echo "... hadrontherapy"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... hadrontherapy.o"
	@echo "... hadrontherapy.i"
	@echo "... hadrontherapy.s"
	@echo "... src/HadrontherapyActionInitialization.o"
	@echo "... src/HadrontherapyActionInitialization.i"
	@echo "... src/HadrontherapyActionInitialization.s"
	@echo "... src/HadrontherapyDetectorHit.o"
	@echo "... src/HadrontherapyDetectorHit.i"
	@echo "... src/HadrontherapyDetectorHit.s"
	@echo "... src/HadrontherapyDetectorMessenger.o"
	@echo "... src/HadrontherapyDetectorMessenger.i"
	@echo "... src/HadrontherapyDetectorMessenger.s"
	@echo "... src/HadrontherapyDetectorROGeometry.o"
	@echo "... src/HadrontherapyDetectorROGeometry.i"
	@echo "... src/HadrontherapyDetectorROGeometry.s"
	@echo "... src/HadrontherapyDetectorSD.o"
	@echo "... src/HadrontherapyDetectorSD.i"
	@echo "... src/HadrontherapyDetectorSD.s"
	@echo "... src/HadrontherapyEventAction.o"
	@echo "... src/HadrontherapyEventAction.i"
	@echo "... src/HadrontherapyEventAction.s"
	@echo "... src/HadrontherapyLet.o"
	@echo "... src/HadrontherapyLet.i"
	@echo "... src/HadrontherapyLet.s"
	@echo "... src/HadrontherapyMatrix.o"
	@echo "... src/HadrontherapyMatrix.i"
	@echo "... src/HadrontherapyMatrix.s"
	@echo "... src/HadrontherapyPhysicsList.o"
	@echo "... src/HadrontherapyPhysicsList.i"
	@echo "... src/HadrontherapyPhysicsList.s"
	@echo "... src/HadrontherapyPrimaryGeneratorAction.o"
	@echo "... src/HadrontherapyPrimaryGeneratorAction.i"
	@echo "... src/HadrontherapyPrimaryGeneratorAction.s"
	@echo "... src/HadrontherapyRunAction.o"
	@echo "... src/HadrontherapyRunAction.i"
	@echo "... src/HadrontherapyRunAction.s"
	@echo "... src/HadrontherapyStepMax.o"
	@echo "... src/HadrontherapyStepMax.i"
	@echo "... src/HadrontherapyStepMax.s"
	@echo "... src/HadrontherapySteppingAction.o"
	@echo "... src/HadrontherapySteppingAction.i"
	@echo "... src/HadrontherapySteppingAction.s"
	@echo "... src/PassiveProtonBeamLine.o"
	@echo "... src/PassiveProtonBeamLine.i"
	@echo "... src/PassiveProtonBeamLine.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

